GestorPaciente/Controllers/Admin/MedicoController.cs
using GestorPaciente.Core.Application.Helpers;
using GestorPaciente.Core.Application.Interfaces.Services;
using GestorPaciente.Core.Application.ViewModels.Medicos;
using GestorPaciente.Middlewares;
using Microsoft.AspNetCore.Mvc;

namespace GestorPaciente.Controllers.Admin
{
    public class MedicoController : Controller
    {

        private readonly IMedicoService _medicoService;
        private readonly ValidateUserSession _userSession;

        public MedicoController(IMedicoService medicoService, ValidateUserSession userSession)
        {
            _medicoService = medicoService;
            _userSession = userSession;
        }


        public async Task<IActionResult> Index()
        {
            if (!_userSession.HasUserAdmin())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            return View(await _medicoService.GetAllViewModel());
        }

        [HttpGet]
        public IActionResult AgregarMedico()
        {
            if (!_userSession.HasUserAdmin())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            return View(new SaveMedicoViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AgregarMedico(SaveMedicoViewModel vm)
        {
            if (!_userSession.HasUserAdmin())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            SaveMedicoViewModel medicoVm = await _medicoService.Add(vm);

            if (medicoVm != null && medicoVm.Id != 0)
            {

                medicoVm.ImageUrl = FileManager.UploadFile(vm.File, medicoVm.Id);

                await _medicoService.Update(medicoVm, medicoVm.Id);
            }
            else
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> EditarMedico(int? id)
        {
            if (!_userSession.HasUserAdmin())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if (id == null)
            {
                return NotFound();
            }

            SaveMedicoViewModel medico = await _medicoService.GetByIdSaveViewModel((int)id);

            if (medico == null)
            {
                return NotFound();
            }

            return View(medico);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditarMedico(SaveMedicoViewModel vm)
        {
            if (!_userSession.HasUserAdmin())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            SaveMedicoViewModel medico = await _medicoService.GetByIdSaveViewModel(vm.Id);

            vm.ImageUrl = FileManager.UploadFile(vm.File, vm.Id, true, medico.ImageUrl);
            await _medicoService.Update(vm, vm.Id);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> EliminarMedico(int id)
        {
            if (!_userSession.HasUserAdmin())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            return View(await _medicoService.GetByIdSaveViewModel(id));
        }

        [HttpPost, ActionName("EliminarMedico")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Eliminar(int id)
        {
            if (!_userSession.HasUserAdmin())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            await _medicoService.Delete(id);
            string basePath = $"/Images/People/{id}";
            string path = Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot{basePath}");

            if (Directory.Exists(path))
            {
                DirectoryInfo directory = new(path);

                foreach (FileInfo file in directory.GetFiles())
                {
                    file.Delete();
                }
                foreach (DirectoryInfo folder in directory.GetDirectories())
                {
                    folder.Delete(true);
                }

            }

            return RedirectToAction(nameof(Index));
        }
    }
}

GestorPaciente/Controllers/Admin/UsuarioController.cs
using GestorPaciente.Core.Application.Interfaces.Services;
using GestorPaciente.Core.Application.ViewModels.Usuario;
using GestorPaciente.Middlewares;
using Microsoft.AspNetCore.Mvc;

namespace GestorPaciente.Controllers.Admin
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioService _usuarioService;
        private readonly ValidateUserSession _userSession;

        public UsuarioController(IUsuarioService usuarioService, ValidateUserSession userSession)
        {
            _usuarioService = usuarioService;
            _userSession = userSession;
        }

        public async Task<IActionResult> Index()
        {
            if (!_userSession.HasUserAdmin())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }
            
            return View(await _usuarioService.GetAllViewModel());
        }

       
        public IActionResult AgregarUsuario()
        {
            if (!_userSession.HasUserAdmin())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            return View(new SaveUsuarioViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AgregarUsuario(SaveUsuarioViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            if(await _usuarioService.UserNameExists(vm.UserName))
            {
                ModelState.AddModelError("UserName", "El nombre de usuario ya existe");
                return View(vm);
            }

            await _usuarioService.Add(vm);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> EditarUsuario(int? id)
        {
            if (!_userSession.HasUserAdmin())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if (id == null)
            {
                return NotFound();
            }

            SaveUsuarioViewModel usuario = await _usuarioService.GetByIdSaveViewModel((int)id);

            if(usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditarUsuario(SaveUsuarioViewModel vm)
        {
            if (ModelState.IsValid)
            {
                await _usuarioService.Update(vm, vm.Id);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> EliminarUsuario(int? id)
        {
            if (!_userSession.HasUserAdmin())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if (id == null)
            {
                return NotFound();
            }

            SaveUsuarioViewModel usuario = await _usuarioService.GetByIdSaveViewModel((int)id);

            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        [HttpPost, ActionName("EliminarUsuario")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            SaveUsuarioViewModel usuario = await _usuarioService.GetByIdSaveViewModel((int)id);

            if (usuario == null)
            {
                return View();
            }

            //borrado
            await _usuarioService.Delete(usuario.Id);

            return RedirectToAction(nameof(Index));
        }


    }
}

GestorPaciente/Controllers/Asistente/CitaController.cs
using GestorPaciente.Core.Application.Interfaces.Services;
using GestorPaciente.Core.Application.ViewModels.Citas;
using GestorPaciente.Core.Application.ViewModels.ResultadosLaboratorio;
using GestorPaciente.Middlewares;
using Microsoft.AspNetCore.Mvc;

namespace GestorPaciente.Controllers.Asistente
{
    public class CitaController : Controller
    {
        private readonly ICitaService _citaService;
        private readonly ValidateUserSession _userSession;
        private readonly IResultadoLaboratorioService _resultadoLaboratorioService;
        private readonly IPruebaLaboratorioService _pruebaLaboratorioService;
        private readonly IPacienteService _pacienteService;
        private readonly IMedicoService _medicoService;

        public CitaController(ICitaService citaService, ValidateUserSession userSession, IResultadoLaboratorioService resultadoLaboratorioService, IPacienteService pacienteService, IMedicoService medicoService, IPruebaLaboratorioService pruebaLaboratorioService)
        {
            _citaService = citaService;
            _userSession = userSession;
            _resultadoLaboratorioService = resultadoLaboratorioService;
            _pruebaLaboratorioService = pruebaLaboratorioService;
            _pacienteService = pacienteService;
            _medicoService = medicoService;
        }

        public async Task<IActionResult> Index()
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            return View(await _citaService.GetAllViewModel());
        }

        [HttpGet]
        public async Task<IActionResult> AgregarCita()
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            SaveCitaViewModel vm = new();
            vm.Pacientes = await _pacienteService.GetAllViewModel();
            vm.Medicos = await _medicoService.GetAllViewModel();

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AgregarCita(SaveCitaViewModel vm)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            await _citaService.Add(vm);

            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        public async Task<IActionResult> SeleccionarPruebas(int id)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            AsignarPruebaViewModel vm = new();

            vm.Pruebas = await _pruebaLaboratorioService.GetAllViewModel();
            vm.CitaId = id;

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SeleccionarPruebas(AsignarPruebaViewModel vm)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            SaveCitaViewModel cita = await _citaService.GetByIdSaveViewModel(vm.CitaId);

            if (cita != null)
            {
                cita.PendingQuery = false;
                cita.PendingResult = true;

                await _citaService.Update(cita, cita.Id);
            }

            await _resultadoLaboratorioService.AddAllSelect(vm, vm.CitaId);

           

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> EliminarCita(int? id)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if(id == null)
            {
                return NotFound();
            }
            
            SaveCitaViewModel cita = await _citaService.GetByIdSaveViewModel((int)id);

            if (cita == null)
            {
                return NotFound();
            }


            cita.Pacientes = await _pacienteService.GetAllViewModel();
            cita.Medicos = await _medicoService.GetAllViewModel();

            return View(cita);
        }

        [HttpPost, ActionName("EliminarCita")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Eliminar(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            SaveCitaViewModel cita = await _citaService.GetByIdSaveViewModel((int)id);

            if (cita == null)
            {
                return NotFound();
            }

            await _citaService.Delete(cita.Id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> CompletarCita(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            SaveCitaViewModel cita = await _citaService.GetByIdSaveViewModel((int)id);

            if (cita == null)
            {
                return NotFound();
            }

            cita.Complete = true;
            cita.PendingQuery = false;
            cita.PendingResult = false;

            await _citaService.Update(cita, cita.Id);

            return RedirectToAction(nameof(Index));
        }
        
    }
}

GestorPaciente/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.datatable.net/1.10.20/css/jquery,dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestorPaciente.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Administrador">Gestor de Paciente</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medico" asp-action="Index">Medicos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PruebaLaboratorio" asp-action="Index">Pruebas de Laboratorio</a>
                        </li>
                        <li class="nav-item align-content-end">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="Home" asp-action="LogOut">Cerrar session</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GestorPaciente 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GestorPaciente/Views/Shared/_AsistentLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.datatable.net/1.10.20/css/jquery,dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestorPaciente.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Asistente">Gestor de Paciente</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paciente" asp-action="Index">Pacientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cita" asp-action="Index">Citas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ResultadoLaboratorio" asp-action="Index">Resultados de Laboratorio</a>
                        </li>
                        <li class="nav-item align-content-end">
                            <a class="nav-link text-dark fw-bold" asp-area="" asp-controller="Home" asp-action="LogOut">Cerrar session</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GestorPaciente 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GestorPaciente/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestorPaciente</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.datatable.net/1.10.20/css/jquery,dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestorPaciente.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GestorPaciente</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GestorPaciente 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>