GestorPaciente/Controllers/Asistente/CitaController.cs
using GestorPaciente.Core.Application.Interfaces.Services;
using GestorPaciente.Core.Application.ViewModels.Citas;
using GestorPaciente.Core.Application.ViewModels.ResultadosLaboratorio;
using GestorPaciente.Middlewares;
using Microsoft.AspNetCore.Mvc;

namespace GestorPaciente.Controllers.Asistente
{
    public class CitaController : Controller
    {
        private readonly ICitaService _citaService;
        private readonly ValidateUserSession _userSession;
        private readonly IResultadoLaboratorioService _resultadoLaboratorioService;
        private readonly IPruebaLaboratorioService _pruebaLaboratorioService;
        private readonly IPacienteService _pacienteService;
        private readonly IMedicoService _medicoService;

        public CitaController(ICitaService citaService, ValidateUserSession userSession, IResultadoLaboratorioService resultadoLaboratorioService, IPacienteService pacienteService, IMedicoService medicoService, IPruebaLaboratorioService pruebaLaboratorioService)
        {
            _citaService = citaService;
            _userSession = userSession;
            _resultadoLaboratorioService = resultadoLaboratorioService;
            _pruebaLaboratorioService = pruebaLaboratorioService;
            _pacienteService = pacienteService;
            _medicoService = medicoService;
        }

        public async Task<IActionResult> Index()
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            return View(await _citaService.GetAllViewModel());
        }

        [HttpGet]
        public async Task<IActionResult> AgregarCita()
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            SaveCitaViewModel vm = new();
            vm.Pacientes = await _pacienteService.GetAllViewModel();
            vm.Medicos = await _medicoService.GetAllViewModel();

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AgregarCita(SaveCitaViewModel vm)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            await _citaService.Add(vm);

            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        public async Task<IActionResult> SeleccionarPruebas(int id)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            AsignarPruebaViewModel vm = new();

            vm.Pruebas = await _pruebaLaboratorioService.GetAllViewModel();
            vm.CitaId = id;

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SeleccionarPruebas(AsignarPruebaViewModel vm)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            SaveCitaViewModel cita = await _citaService.GetByIdSaveViewModel(vm.CitaId);

            if (cita != null)
            {
                cita.PendingQuery = false;
                cita.PendingResult = true;

                await _citaService.Update(cita, cita.Id);
            }

            await _resultadoLaboratorioService.AddAllSelect(vm, vm.CitaId);

           

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> EliminarCita(int? id)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if(id == null)
            {
                return NotFound();
            }
            
            SaveCitaViewModel cita = await _citaService.GetByIdSaveViewModel((int)id);

            if (cita == null)
            {
                return NotFound();
            }


            cita.Pacientes = await _pacienteService.GetAllViewModel();
            cita.Medicos = await _medicoService.GetAllViewModel();

            return View(cita);
        }

        [HttpPost, ActionName("EliminarCita")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Eliminar(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            SaveCitaViewModel cita = await _citaService.GetByIdSaveViewModel((int)id);

            if (cita == null)
            {
                return NotFound();
            }

            await _citaService.Delete(cita.Id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> CompletarCita(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            SaveCitaViewModel cita = await _citaService.GetByIdSaveViewModel((int)id);

            if (cita == null)
            {
                return NotFound();
            }

            cita.Complete = true;
            cita.PendingQuery = false;
            cita.PendingResult = false;

            await _citaService.Update(cita, cita.Id);

            return RedirectToAction(nameof(Index));
        }
        
    }
}

GestorPaciente/Controllers/Asistente/ResultadoLaboratorioController.cs
using GestorPaciente.Core.Application.Interfaces.Services;
using GestorPaciente.Core.Application.ViewModels.Citas;
using GestorPaciente.Core.Application.ViewModels.ResultadosLaboratorio;
using GestorPaciente.Middlewares;
using Microsoft.AspNetCore.Mvc;

namespace GestorPaciente.Controllers.Asistente
{
    public class ResultadoLaboratorioController : Controller
    {
        private readonly IResultadoLaboratorioService _resultadoLaboratorioService;
        private readonly ICitaService _citaService;
        private readonly IPacienteService _pacienteService;
        private readonly IPruebaLaboratorioService _pruebaLaboratorioService;
        private readonly ValidateUserSession _userSession;

        public ResultadoLaboratorioController (IResultadoLaboratorioService resultadoLaboratorioService, ValidateUserSession userSession, ICitaService citaService, IPacienteService pacienteService, IPruebaLaboratorioService pruebaLaboratorioService)
        {
            _resultadoLaboratorioService = resultadoLaboratorioService;
            _userSession = userSession;
            _citaService = citaService;
            _pacienteService = pacienteService;
            _pruebaLaboratorioService = pruebaLaboratorioService;
        }

        public async Task<IActionResult> Index()
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            var resultados = await _resultadoLaboratorioService.GetAllViewModel();

            resultados = resultados.Where(item => item.Pending).ToList();

            foreach (ResultadoLaboratorioViewModel item in resultados)
            {
                item.Paciente = item.Cita.Paciente;  /*_pacienteService.GetById(item.Cita.PacienteId);*/
            }

            return View(resultados);
        }

        public async Task<IActionResult> VerResultadoCita(int? id)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if (id == null)
            {
                return NotFound();
            }

            var resultados = await _resultadoLaboratorioService.GetAllViewModel();

            resultados = resultados.Where(item => item.Cita.Id == id).ToList();

            foreach (ResultadoLaboratorioViewModel item in resultados)
            {
                item.Paciente = item.Cita.Paciente;
            }

            return View(resultados);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FiltrarCedula(string cedula)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if(cedula == null)
            {
                return NotFound();
            }

            var resultados = await _resultadoLaboratorioService.GetAllViewModel();

            foreach (ResultadoLaboratorioViewModel item in resultados)
            {
                item.Paciente = item.Cita.Paciente;  
            }

            resultados = resultados.Where(item => item.Paciente.Cedula == cedula).ToList();

            return View("Index", resultados);
        }

        [HttpGet]
        public async Task<IActionResult> CompletarResultadoLaboratorio(int? id)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if (id == null)
            {
                return NotFound();
            }

            SaveResultadoLaboratorioViewModel resultado = await _resultadoLaboratorioService.GetByIdSaveViewModel((int)id);

            if(resultado == null)
            {
                return NotFound();
            }

            return View(resultado);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CompletarResultadoLaboratorio(SaveResultadoLaboratorioViewModel vm)
        {
            if(!ModelState.IsValid)
            {
                return View(vm);
            }

            await _resultadoLaboratorioService.Update(vm, vm.Id);

            return RedirectToAction(nameof(Index));
        }

        
        [HttpGet]
        public async Task<IActionResult> VerResultadoLaboratorio(int? id)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if(id  == null)
            {
                return NotFound();
            }

            SaveResultadoLaboratorioViewModel resultado = await _resultadoLaboratorioService.GetByIdSaveViewModel((int)id);

            if (resultado == null)
            {
                return NotFound();
            }

            return View(resultado);
        }

    }
}

GestorPaciente/Views/Cita/AgregarCita.cshtml
@using GestorPaciente.Core.Application.ViewModels.Citas;
@model SaveCitaViewModel
@{
    ViewData["Title"] = "Agregar Cita";
}

<div class="container-fluid">

    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                @if (Model.Pacientes != null && Model.Medicos != null)
                {
                    <div class="card-header bg-dark text-light">
                        <h4>Agregar Cita</h4>
                    </div>
                    <div class="card-body">

                        <form method="post" asp-controller="Cita" asp-action="AgregarCita" enctype="multipart/form-data">

                            <div class="mb-3">
                                <label asp-for="PacienteId" class="form-label">Paciente: </label>
                                <select asp-for="PacienteId" asp-items="@(new SelectList(Model.Pacientes,"Id","Name","LastName"))" class="form-select">
                                    <option value="0">Seleccione un Paciente</option>

                                </select>
                                <span asp-validation-for="PacienteId" class="text-danger"></span>
                            </div>

                            <div class="mb-3">
                                <label asp-for="MedicoId" class="form-label">Medicos: </label>
                                <select asp-for="MedicoId" asp-items="@(new SelectList(Model.Medicos,"Id","Name","LastName"))" class="form-select">
                                    <option value="0">Seleccione un Medico</option>

                                </select>
                                <span asp-validation-for="MedicoId" class="text-danger"></span>
                            </div>

                            <div class="mb-3">
                                <label asp-for="cause" class="form-label">Causa: </label>
                                <textarea asp-for="cause" class="form-control"></textarea>
                            </div>

                            <div class="mb-3">
                                <label asp-for="Date" class="form-label">Fecha de nacimiento: (DD/MM/AAAA)</label>
                                <input type="date" asp-for="Date" class="form-control" />
                                <span asp-validation-for="Date" class="text-danger"></span>
                            </div>

                            <div class="mb-3">
                                <label asp-for="Hour" class="form-label">Hora: </label>
                                <input type="time" asp-for="Hour" class="form-control" />
                                <span asp-validation-for="Hour" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary d-block mx-auto"><i class="bi bi-plus-circle-fill"></i>Crear Cita</button>
                            </div>

                        </form>
                        <a asp-controller="Cita" asp-action="Index">Volver</a>

                    </div>
                }
                else
                {
                    <ul class="mb-3">
                        @if (Model.Pacientes == null)
                        {
                            <li>No hay paciente registrados</li>
                        }
                        @if (Model.Medicos == null)
                        {
                            <li>No hay Medicos registrados</li>
                        }
                    </ul>

                    <a asp-controller="Cita" asp-action="Index">Volver</a>
                }
            </div>
        </div>
    </div>

</div>

GestorPaciente/Views/Cita/CompletarCita.cshtml
@using GestorPaciente.Core.Application.ViewModels.ResultadosLaboratorio;
@model SaveResultadoLaboratorioViewModel;
@{
    Layout = "_AsistentLayout";
    ViewData["Title"] = "Ver Resultado";
}

<div class="container-fluid">

    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                @if (Model != null)
                {
                    <div class="card-header bg-dark text-light">
                        <h4>Ver Resultado</h4>
                    </div>
                    <div class="card-body">

                        <form method="post" asp-controller="ResultadoLaboratorio" asp-action="CompletarResultadoLaboratorio">

                            <input type="hidden" asp-for=@Model.Id />

                            <input type="hidden" asp-for=@Model.CitaId />

                            <input type="hidden" asp-for=@Model.PruebaLaboratorioId />

                            <div class="mb-3">
                                <label asp-for="Result" class="form-label">Resultado: </label>
                                <textarea asp-for="Result" class="form-control" readonly></textarea>
                                <span asp-validation-for="Result" class="text-danger"></span>
                            </div>

                            <input type="hidden" asp-for="Pending" value=false />
                        </form>

                        <a asp-controller="Cita" asp-action="Index">Volver</a>

                    </div>
                }
                else
                {
                    <p>No se encontro Prueba</p>

                    <a asp-controller="Cita" asp-action="Index">Volver</a>
                }
            </div>
        </div>
    </div>

</div>

GestorPaciente/Views/Cita/EliminarCita.cshtml
@using GestorPaciente.Core.Application.ViewModels.Citas;
@model SaveCitaViewModel
@{
    ViewData["Title"] = "Eliminar Cita";
}

<div class="container-fluid">

    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                @if (Model.Pacientes != null && Model.Medicos != null)
                {
                    <div class="card-header bg-dark text-light">
                        <h4>Eliminar Cita</h4>
                    </div>
                    <div class="card-body">

                        <form method="post" asp-controller="Cita" asp-action="EliminarCita" enctype="multipart/form-data">

                            <div class="mb-3">
                                <label asp-for="PacienteId" class="form-label">Paciente: </label>
                                <select asp-for="PacienteId" asp-items="@(new SelectList(Model.Pacientes,"Id","Name","LastName"))" class="form-select" readonly>
                                    <option value="0" readonly>Seleccione un Paciente</option>

                                </select>
                                <span asp-validation-for="PacienteId" class="text-danger"></span>
                            </div>

                            <div class="mb-3">
                                <label asp-for="MedicoId" class="form-label">Medicos: </label>
                                <select asp-for="MedicoId" asp-items="@(new SelectList(Model.Medicos,"Id","Name","LastName"))" class="form-select" readonly>
                                    <option value="0" readonly>Seleccione un Medico</option>

                                </select>
                                <span asp-validation-for="MedicoId" class="text-danger"></span>
                            </div>

                            <div class="mb-3">
                                <label asp-for="cause" class="form-label">Causa: </label>
                                <textarea asp-for="cause" class="form-control" readonly></textarea>
                            </div>

                            <div class="mb-3">
                                <label asp-for="Date" class="form-label">Fecha de nacimiento: (DD/MM/AAAA)</label>
                                <input type="date" asp-for="Date" class="form-control" readonly/>
                                <span asp-validation-for="Date" class="text-danger"></span>
                            </div>

                            <div class="mb-3">
                                <label asp-for="Hour" class="form-label">Hora: </label>
                                <input type="time" asp-for="Hour" class="form-control" readonly/>
                                <span asp-validation-for="Hour" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-danger d-block mx-auto"><i class="bi bi-plus-circle-fill"></i>Eliminar</button>
                            </div>

                        </form>
                        <a asp-controller="Cita" asp-action="Index">Volver</a>

                    </div>
                }
                else
                {
                    <ul class="mb-3">
                        @if (Model.Pacientes == null)
                        {
                            <li>No hay paciente registrados</li>
                        }
                        @if (Model.Medicos == null)
                        {
                            <li>No hay Medicos registrados</li>
                        }
                    </ul>

                    <a asp-controller="Cita" asp-action="Index">Volver</a>
                }
            </div>
        </div>
    </div>

</div>

GestorPaciente/Views/Cita/Index.cshtml
@using GestorPaciente.Core.Application.ViewModels.Citas;
@model List<CitaViewModel>;
@{
    Layout = "_AsistentLayout";
    ViewData["Title"] = "Citas";
}

<div class="row mb-3">
    <div class="col-3 offset-9">
        <a asp-action="AgregarCita" asp-controller="Cita" class="btn btn-outline-secondary d-block mx-auto">
            <i class="bi bi-file-plus-fill"></i> Agregar Cita
        </a>
    </div>
</div>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Lista de Citas</strong></h3>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @if (Model != null && Model.Count > 0)
                    {
                        <table class="table table-bordered" id="tblcitas" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Paciente</th>
                                    <th>Medico</th>
                                    <th>Fecha</th>
                                    <th>Causa</th>
                                    <th>Estado</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="col-2">@Html.DisplayFor(m => item.Paciente.Name) @Html.DisplayFor(m => item.Paciente.LastName)</td>
                                        <td class="col-2">@Html.DisplayFor(m => item.Medico.Name) @Html.DisplayFor(m => item.Medico.LastName)</td>
                                        <td class="col-1">@Html.DisplayFor(m => item.Date)  @Html.DisplayFor(m => item.Hour)</td>
                                        <td class="col-4">@Html.DisplayFor(m => item.cause)</td>
                                        
                                        <td class="col-1">
                                            @if (item.Complete)
                                            {
                                                <text>Completada</text>
                                            }
                                            @if(item.PendingQuery)
                                            {
                                                <text>Sin Asignar</text>
                                            }
                                            @if(item.PendingResult)
                                            {
                                                <text>Esperando Resultados</text>
                                            }
                                        </td>
                                        <td class="col-2 align-content-center">
                                            @if (item.PendingQuery)
                                            {
                                                <a class="btn btn-primary btn-sm" asp-controller="Cita" asp-action="SeleccionarPruebas" asp-route-id="@item.Id">
                                                    <i class="bi bi-file-plus-fill"></i> Agregar Prueba
                                                </a>
                                            }
                                            @if (item.PendingResult)
                                            {
                                                <a class="btn btn-warning btn-sm" asp-controller="ResultadoLaboratorio" asp-action="VerResultadoCita" asp-route-id="@item.Id">
                                                    <i class="bi bi-hourglass-bottom"></i> Ver Pruebas
                                                </a>
                                            }
                                            @if (item.Complete)
                                            {
                                                <a class="btn btn-success btn-sm" asp-controller="ResultadoLaboratorio" asp-action="VerResultadoCita" asp-route-id="@item.Id">
                                                    <i class="bi bi-check-circle-fill"></i> Completada
                                                </a>
                                            }else{
                                                <a class="btn btn-danger btn-sm" asp-controller="Cita" asp-action="EliminarCita" asp-route-id="@item.Id">
                                                    <i class="bi bi-eraser-fill"></i> Eliminar
                                                </a>
                                            }
                                            
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <p>No hay citas programadas</p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

GestorPaciente/Views/Cita/SeleccionarPruebas.cshtml
@using GestorPaciente.Core.Application.ViewModels.ResultadosLaboratorio;
@model AsignarPruebaViewModel
@{
    ViewData["Title"] = "Seleccionar Pruebas";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                @if (Model.Pruebas != null && Model.Pruebas.Any())
                {
                    <div class="card-header bg-dark text-light">
                        <h4>Asignar pruebas</h4>
                    </div>
                    <div class="card-body">
                        <div class="mb-3">
                            <form method="post" asp-controller="Cita" asp-action="SeleccionarPruebas" enctype="multipart/form-data">
                                <span asp-validation-for="PruebasSelesccionadas" class="text-danger"></span>
                                <label class="mb-3">Pruebas de laboratorio:</label>
                                @foreach (var prueba in Model.Pruebas)
                                {
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" id="@("prueba_" + prueba.Id)" name="PruebasSelesccionadas" value="@prueba.Id" />
                                        <label class="form-check-label" for="@("prueba_" + prueba.Id)">
                                            @prueba.Name
                                        </label>
                                    </div>
                                }

                                <input type="hidden" asp-for="CitaId" value="@Model.CitaId"/>

                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary d-block mx-auto"><i class="bi bi-plus-circle-fill"></i>Asignar</button>
                                </div>
                            </form>
                            <a asp-controller="Cita" asp-action="Index">Volver</a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>