GestorPaciente/Controllers/Admin/PruebaLaboratorioController.cs
using GestorPaciente.Core.Application.Interfaces.Services;
using GestorPaciente.Core.Application.ViewModels.PruebasLaboratorio;
using GestorPaciente.Middlewares;
using Microsoft.AspNetCore.Mvc;

namespace GestorPaciente.Controllers.Admin
{
    public class PruebaLaboratorioController : Controller
    {

        private readonly IPruebaLaboratorioService _PruebaLaboratorioService;
        private readonly ValidateUserSession _userSession;

        public PruebaLaboratorioController(IPruebaLaboratorioService pruebaLaboratorioService, ValidateUserSession userSession)
        {
            _PruebaLaboratorioService = pruebaLaboratorioService;
            _userSession = userSession;
        }

        public async Task<IActionResult> Index()
        {
            if (!_userSession.HasUserAdmin())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            return View(await _PruebaLaboratorioService.GetAllViewModel());
        }

        public IActionResult AgregarPruebaLaboratorio()
        {
            if (!_userSession.HasUserAdmin())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            return View(new SavePruebaLaboratorioViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AgregarPruebaLaboratorio(SavePruebaLaboratorioViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            await _PruebaLaboratorioService.Add(vm);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> EditarPruebaLaboratorio(int? id)
        {
            if (!_userSession.HasUserAdmin())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if(id == null)
            {
                return NotFound();
            }

            SavePruebaLaboratorioViewModel prueba = await  _PruebaLaboratorioService.GetByIdSaveViewModel((int)id);

            if (prueba == null)
            {
                return NotFound();
            }
 
            return View(prueba);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditarPruebaLaboratorio(SavePruebaLaboratorioViewModel vm)
        {
            if (ModelState.IsValid)
            {
                await _PruebaLaboratorioService.Update(vm, vm.Id);
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> EliminarPruebaLaboratorio(int? id)
        {
            if (!_userSession.HasUserAdmin())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if(id == null)
            {
                return NotFound();
            }

            SavePruebaLaboratorioViewModel prueba = await _PruebaLaboratorioService.GetByIdSaveViewModel((int)id);

            if (prueba == null)
            {
                return NotFound();
            }

            return View(prueba);
        }

        [HttpPost, ActionName("EliminarPruebaLaboratorio")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            SavePruebaLaboratorioViewModel prueba = await _PruebaLaboratorioService.GetByIdSaveViewModel((int)id);

            if (prueba == null)
            {
                return View();
            }

            //borrado
            await _PruebaLaboratorioService.Delete(prueba.Id);

            return RedirectToAction(nameof(Index));
        }


    }
}

GestorPaciente/Views/PruebaLaboratorio/AgregarPruebaLaboratorio.cshtml
@using GestorPaciente.Core.Application.ViewModels.PruebasLaboratorio;
@model SavePruebaLaboratorioViewModel
@{
    Layout = "_AdminLayout";
    ViewData["Title"] = "Agregar Prueba de Laboratorio";
}

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Agregar Prueba de Laboratorio</strong></h3>
            </div>
            <div class="card-body">
                <form asp-action="AgregarPruebaLaboratorio" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="mb-3">
                        <label asp-for="Name" class="form-label">Nombre: </label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary d-block mx-auto"><i class="bi bi-plus-circle-fill"></i>Agregar</button>
                    </div>

                </form>

                <a asp-controller="PruebaLaboratorio" asp-action="Index">Volver</a>
            </div>
        </div>
    </div>
</div>

GestorPaciente/Views/PruebaLaboratorio/EditarPruebaLaboratorio.cshtml
@using GestorPaciente.Core.Application.ViewModels.PruebasLaboratorio;
@model SavePruebaLaboratorioViewModel
@{
    Layout = "_AdminLayout";
    ViewData["Title"] = "Editar Prueba de Laboratorio";
}

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Editar Prueba de Laboratorio</strong></h3>
            </div>
            <div class="card-body">
                <form asp-action="EditarPruebaLaboratorio" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="mb-3">
                        <label asp-for="Name" class="form-label">Nombre: </label>
                        <input asp-for="Name" class="form-control"/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-warning d-block mx-auto"><i class="bi bi-pensil-fill"></i>Editar</button>
                    </div>

                </form>

                <a asp-controller="PruebaLaboratorio" asp-action="Index">Volver</a>
            </div>
        </div>
    </div>
</div>

GestorPaciente/Views/PruebaLaboratorio/EliminarPruebaLaboratorio.cshtml
@using GestorPaciente.Core.Application.ViewModels.PruebasLaboratorio;
@model SavePruebaLaboratorioViewModel
@{
    Layout = "_AdminLayout";
    ViewData["Title"] = "Eliminar Prueba de Laboratorio";
}

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Seguro que desea eliminar esta prueba?</strong></h3>
            </div>
            <div class="card-body">
                <form asp-action="EliminarPruebaLaboratorio" method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="mb-3">
                        <label asp-for="Name" class="form-label">Nombre: </label>
                        <input asp-for="Name" class="form-control" readonly/>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-danger d-block mx-auto"><i class="bi bi-eraser-fill"></i>Eliminar</button>
                    </div>

                </form>

                <a asp-controller="PruebaLaboratorio" asp-action="Index">Volver</a>
            </div>
        </div>
    </div>
</div>

GestorPaciente/Views/PruebaLaboratorio/Index.cshtml
@using GestorPaciente.Core.Application.ViewModels.PruebasLaboratorio;
@model List<PruebaLaboratorioViewModel>;
@{
    Layout = "_AdminLayout";
    ViewData["Title"] = "Pruebas de Laboratorio";
}

<div class="row mb-3">
    <div class="col-3 offset-9">
        <a asp-action="AgregarPruebaLaboratorio" asp-controller="PruebaLaboratorio" class="btn btn-outline-secondary d-block mx-auto">
            <i class="bi bi-file-plus-fill"></i> Agregar Prueba de laboratorio
        </a>
    </div>
</div>

<div class="row">
    <div class="offset-12">
        <div class="card border">
            <div class="card-header bg-dark">
                <h3 class="text-white"><strong>Lista de Pruebas de laboratorio</strong></h3>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @if (Model != null && Model.Count > 0)
                    {
                        <table class="table table-bordered" id="tblUsuarios" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Nombre</th>
                                    <th>Aciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="col-4">@Html.DisplayFor(m => item.Id)</td>
                                        <td class="col-4">@Html.DisplayFor(m => item.Name)</td>
                                        <td class="col-4">
                                            <a class="btn btn-warning btn-sm" asp-action="EditarPruebaLaboratorio" asp-route-id="@item.Id">
                                                <i class="bi bi-pencil-fill"></i> Editar
                                            </a>
                                            <a class="btn btn-danger btn-sm" asp-action="EliminarPruebaLaboratorio" asp-route-id="@item.Id">
                                                <i class="bi bi-eraser-fill"></i> Eliminar
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <p>No hay Registros</p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>