GestorPaciente/Controllers/Asistente/PacienteController.cs
using GestorPaciente.Core.Application.Helpers;
using GestorPaciente.Core.Application.Interfaces.Services;
using GestorPaciente.Core.Application.Services;
using GestorPaciente.Core.Application.ViewModels.Paciente;
using GestorPaciente.Core.Domain.Entities;
using GestorPaciente.Middlewares;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.CompilerServices;

namespace GestorPaciente.Controllers.Asistente
{
    public class PacienteController : Controller
    {
        private readonly IPacienteService _pacienteService;
        private readonly ValidateUserSession _userSession;

        public PacienteController(IPacienteService pacienteService, ValidateUserSession userSession)
        {
            _pacienteService = pacienteService;
            _userSession = userSession;
        }


        public async Task<IActionResult> Index()
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            return View(await _pacienteService.GetAllViewModel());
        }

        [HttpGet]
        public IActionResult AgregarPaciente()
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            return View(new SavePacienteViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AgregarPaciente(SavePacienteViewModel vm)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            SavePacienteViewModel paciente = await _pacienteService.Add(vm);

            if (paciente != null && paciente.Id != 0)
            {
                paciente.ImageUrl = FileManager.UploadFile(vm.File, paciente.Id);
                await _pacienteService.Update(paciente, paciente.Id);
            }
            else
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> EditarPaciente(int? id)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if (id == null)
            {
                return NotFound();

            }

            SavePacienteViewModel paciente = await _pacienteService.GetByIdSaveViewModel((int)id);

            if (paciente == null)
            {
                return NotFound();
            }


            return View(paciente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditarPaciente(SavePacienteViewModel vm)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            if(!ModelState.IsValid)
            {
                return View(vm);
            }

            SavePacienteViewModel paciente = await _pacienteService.GetByIdSaveViewModel(vm.Id);

            vm.ImageUrl = FileManager.UploadFile(vm.File, vm.Id, true, paciente.ImageUrl);

            await _pacienteService.Update(vm, vm.Id);

            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        public async Task<IActionResult> EliminarPaciente(int id)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            return View(await _pacienteService.GetByIdSaveViewModel(id));
        }

        [HttpPost, ActionName("EliminarPaciente")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Eliminar(int id)
        {
            if (!_userSession.HasUserAsistent())
            {
                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }

            await _pacienteService.Delete(id);
            string basePath = $"/Images/People/{id}";
            string path = Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot{basePath}");

            if (Directory.Exists(path))
            {
                DirectoryInfo directory = new(path);

                foreach (FileInfo file in directory.GetFiles())
                {
                    file.Delete();
                }
                foreach (DirectoryInfo folder in directory.GetDirectories())
                {
                    folder.Delete(true);
                }

            }

            return RedirectToAction(nameof(Index));
        }
    }
}

GestorPaciente/Views/Paciente/AgregarPaciente.cshtml
@using GestorPaciente.Core.Application.ViewModels.Paciente;
@model SavePacienteViewModel
@{
    ViewData["Title"] = "Agregar Paciente";
}

<div class="container-fluid">

    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                <div class="card-header bg-dark text-light">
                    <h4>Agregar Paciente</h4>
                </div>
                <div class="card-body">

                    <form method="post" asp-controller="Paciente" asp-action="AgregarPaciente" enctype="multipart/form-data">

                        <div class="mb-3">
                            <label asp-for="Name" class="form-label">Nombre: </label>
                            <input type="text" asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="LastName" class="form-label">Apellido: </label>
                            <input type="text" asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>

                        <div class ="mb-2">
                            <ul style="list-style-type: none; padding: 0; margin: 0;">
                                <li class="mb-1">
                                    <label>
                                        <input type="checkbox" asp-for="Smoker" />
                                        Fumador
                                    </label>
                                    <span asp-validation-for="Smoker" class="text-danger"></span>
                                </li>
                                <li class="mb-1">
                                    <label>
                                        <input type="checkbox" asp-for="Allergies" />
                                        Alergias
                                    </label>
                                    <span asp-validation-for="Allergies" class="text-danger"></span>
                                </li>
                            </ul>
                            
                        </div>

                        <div class="mb-3">
                            <label asp-for="Phone" class="form-label">Telefono: </label>
                            <input type="text" asp-for="Phone" class="form-control" />
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="Cedula" class="form-label">Cedula: </label>
                            <input type="text" asp-for="Cedula" class="form-control" />
                            <span asp-validation-for="Cedula" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="Direction" class="form-label">Direccion: </label>
                            <input type="text" asp-for="Direction" class="form-control" />
                            <span asp-validation-for="Direction" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="BirhtDate" class="form-label">Fecha de nacimiento: (DD/MM/AAAA)</label>
                            <input type="date" asp-for="BirhtDate" class="form-control" />
                            <span asp-validation-for="BirhtDate" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="File" class="form-label">Seleccione un archivo:</label>

                            <input required asp-for="File" class="form-control" />

                            <span asp-validation-for="File" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary d-block mx-auto"><i class="bi bi-plus-circle-fill"></i>Agregar</button>
                        </div>

                    </form>
                    <a asp-controller="Paciente" asp-action="Index">Volver</a>

                </div>

            </div>
        </div>
    </div>

</div>

GestorPaciente/Views/Paciente/EditarPaciente.cshtml
@using GestorPaciente.Core.Application.ViewModels.Paciente;
@model SavePacienteViewModel
@{
    ViewData["Title"] = "Paciente Medico";
}

<div class="container-fluid">

    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                <div class="card-header bg-dark text-light">
                    <h4>Editar Paciente: @Model.Name @Model.LastName</h4>
                </div>
                <div class="card-body">

                    <form method="post" asp-controller="Paciente" asp-action="EditarPaciente" enctype="multipart/form-data">

                        <div class="mb-3">
                            <label asp-for="Name" class="form-label">Nombre: </label>
                            <input type="text" asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="LastName" class="form-label">Apellido: </label>
                            <input type="text" asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>

                        <div class="mb-2">
                            <ul style="list-style-type: none; padding: 0; margin: 0;">
                                <li class="mb-1">
                                    <label>
                                        <input type="checkbox" asp-for="Smoker" />
                                        Fumador
                                    </label>
                                    <span asp-validation-for="Smoker" class="text-danger"></span>
                                </li>
                                <li class="mb-1">
                                    <label>
                                        <input type="checkbox" asp-for="Allergies" />
                                        Alergias
                                    </label>
                                    <span asp-validation-for="Allergies" class="text-danger"></span>
                                </li>
                            </ul>

                        </div>

                        <div class="mb-3">
                            <label asp-for="Phone" class="form-label">Telefono: </label>
                            <input type="text" asp-for="Phone" class="form-control" />
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="Cedula" class="form-label">Cedula: </label>
                            <input type="text" asp-for="Cedula" class="form-control" />
                            <span asp-validation-for="Cedula" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="Direction" class="form-label">Direccion: </label>
                            <input type="text" asp-for="Direction" class="form-control" />
                            <span asp-validation-for="Direction" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="BirhtDate" class="form-label">Fecha de nacimiento: (DD/MM/AAAA)</label>
                            <input type="date" asp-for="BirhtDate" class="form-control" />
                            <span asp-validation-for="BirhtDate" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="File" class="form-label">Seleccione un archivo:</label>

                            <input asp-for="File" class="form-control" />

                            <span asp-validation-for="File" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-warning d-block mx-auto"><i class="bi bi-pencil-fill"></i>Editar</button>
                        </div>

                    </form>
                    <a asp-controller="Paciente" asp-action="Index">Volver</a>

                </div>

            </div>
        </div>
    </div>

</div>

GestorPaciente/Views/Paciente/EliminarPaciente.cshtml
@using GestorPaciente.Core.Application.ViewModels.Paciente;
@model SavePacienteViewModel
@{
    ViewData["Title"] = "Paciente Medico";
}

<div class="container-fluid">

    <div class="row">
        <div class="col-6 offset-3">
            <div class="card">
                <div class="card-header bg-dark text-light">
                    <h4>Editar Paciente: @Model.Name @Model.LastName</h4>
                </div>
                <div class="card-body">

                    <form method="post" asp-controller="Paciente" asp-action="EliminarPaciente" enctype="multipart/form-data">

                        <div class="mb-3">
                            <label asp-for="Name" class="form-label">Nombre: </label>
                            <input type="text" asp-for="Name" class="form-control" readonly />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="LastName" class="form-label">Apellido: </label>
                            <input type="text" asp-for="LastName" class="form-control" readonly />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>

                        <div class="mb-2">
                            <ul style="list-style-type: none; padding: 0; margin: 0;">
                                <li class="mb-1">
                                    <label>
                                        <input type="checkbox" asp-for="Smoker" readonly />
                                        Fumador
                                    </label>
                                    <span asp-validation-for="Smoker" class="text-danger"></span>
                                </li>
                                <li class="mb-1">
                                    <label>
                                        <input type="checkbox" asp-for="Allergies" readonly />
                                        Alergias
                                    </label>
                                    <span asp-validation-for="Allergies" class="text-danger"></span>
                                </li>
                            </ul>

                        </div>

                        <div class="mb-3">
                            <label asp-for="Phone" class="form-label">Telefono: </label>
                            <input type="text" asp-for="Phone" class="form-control" readonly />
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="Cedula" class="form-label">Cedula: </label>
                            <input type="text" asp-for="Cedula" class="form-control" readonly />
                            <span asp-validation-for="Cedula" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="Direction" class="form-label">Direccion: </label>
                            <input type="text" asp-for="Direction" class="form-control" readonly />
                            <span asp-validation-for="Direction" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="BirhtDate" class="form-label">Fecha de nacimiento: (DD/MM/AAAA)</label>
                            <input type="date" asp-for="BirhtDate" class="form-control" readonly />
                            <span asp-validation-for="BirhtDate" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="File" class="form-label">Seleccione un archivo:</label>

                            <input asp-for="File" class="form-control" readonly />

                            <span asp-validation-for="File" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-danger d-block mx-auto"><i class="bi bi-eraser-fill"></i>Eliminar</button>
                        </div>

                    </form>
                    <a asp-controller="Paciente" asp-action="Index">Volver</a>

                </div>

            </div>
        </div>
    </div>

</div>

GestorPaciente/Views/Paciente/Index.cshtml
@using GestorPaciente.Core.Application.ViewModels.Paciente;
@model List<PacienteViewModel>;
@{
    Layout = "_AsistentLayout";
    ViewData["Title"] = "Medicos";
}

<style>
    .img-container {
        max-width: 100%;
        max-height: 200px;
        overflow: clip;
    }

        .img-container img {
            width: 100%;
            height: 100%;
        }
</style>

<div class="container-fluid">

    <div class="row mb-3">
        <div class="col-3 offset-9">
            <a asp-controller="Paciente" asp-action="AgregarPaciente" class="btn btn-outline-secondary d-block mx-auto"><i class="bi bi-file-plus-fill"></i>Agregar Paciente</a>
        </div>
    </div>

    <div class="row">

        @if (Model == null || Model.Count == 0)
        {
            <h3>No hay Pacientes registrados</h3>
        }
        else
        {
            @foreach (PacienteViewModel item in Model)
            {
                <div class="col-3 mb-3">
                    <div class="card shadow-sm">
                        <div class="img-container">
                            <img class="bd-placeholder-img card-img-top img-product-size" src="@item.ImageUrl" />
                        </div>
                        <div class="card-body">
                            <h5 class="card-title mb-2">@item.Name @item.LastName</h5>
                            <p class="card-text"><strong>Cedula:</strong> @item.Cedula</p>
                            <p class="card-text"><strong>Fecha de Nacimiento:</strong> @item.BirhtDate.ToString("dd/MM/yyyy")</p>
                            <p class="card-text"><strong>Telefono:</strong> @item.Phone</p>
                            <p class="card-text"><strong>Dirrecion:</strong> @item.Direction</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-controller="Paciente" asp-action="EditarPaciente" asp-route-id="@item.Id" class="btn btn-sm btn-outline-warning"><i class="bi bi-pencil-fill"></i>Editar</a>
                                    <a asp-controller="Paciente" asp-action="EliminarPaciente" asp-route-id="@item.Id" class="btn btn-sm btn-outline-danger"><i class="bi bi-eraser-fill"></i>Borrar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>

</div>